import json

def massive_update():
    dict_file = 'translations_en.json'
    try:
        with open(dict_file, 'r', encoding='utf-8') as f:
            d = json.load(f)
    except:
        d = {}

    updates = {
        "價格": "Price",
        "類別": "Category",
        "項目": "Item",
        "檢查說明": "Description",
        "檢驗項目內容": "Examination Content",
        "單項加選": "Add-on Items",
        "詳細清單": "Detailed List",
        "上腹部": "Upper Abdomen",
        "下腹部": "Lower Abdomen",
        "全脊椎": "Full Spine",
        "頸部": "Neck",
        "胸部": "Chest",
        "腰部": "Waist/Lumbar",
        "骨盆腔": "Pelvic",
        "磁振造影": "MRI",
        "電腦斷層": "CT Scan",
        "超音波": "Ultrasound",
        "心血管健康指標": "Cardiovascular Health Markers",
        "糖尿病篩檢": "Diabetes Screening",
        "血脂肪檢查": "Lipid Profile",
        "肝膽功能指標": "Liver Function",
        "腎臟功能指標": "Renal Function",
        "血液常規檢查": "Complete Blood Count",
        "甲狀腺功能指標": "Thyroid Function",
        "血液腫瘤標記": "Tumor Markers",
        "尿液檢查": "Urinalysis",
        "糞便檢查": "Stool Analysis",
        "骨質密度": "Bone Density",
        "腸胃科": "Gastroenterology",
        "心臟科": "Cardiology",
        "眼科": "Ophthalmology",
        "耳鼻喉科": "ENT",
        "婦科(限女性)": "Gynecology (Female Only)",
        "生理量測": "Physical Measurements",
        "胰臟指標": "Pancreatic Markers",
        "肺癌標記": "Lung Cancer Markers",
        "凝血功能": "Coagulation Function",
        "栓塞指數": "Embolism Index",
        "肝炎篩檢": "Hepatitis Screening",
        "類風濕性關節炎篩檢": "Rheumatoid Factor",
        "過敏原檢查": "Allergy Test",
        "荷爾蒙及特殊檢驗": "Hormones & Special Tests",
        "維生素相關": "Vitamins",
        "醫師諮詢": "Physician Consultation",
        "餐點": "Meals",
        "服裝": "Uniform",
        "報告": "Report",
        "交通": "Transportation",
        "輔助高階3T 磁振造影影像診斷": "CAD for High-End 3T MRI",
        "零輻射高階 3T磁振造影": "Zero-Radiation High-End 3T MRI",
        "高階雙源電腦斷層": "High-End Dual-Source CT Scan",
        "1.由放射科醫師與專科醫師共同判讀影像。": "1. Images interpreted by Radiologists and Specialists.",
        "2.由臨床醫師進行理學檢查與初步診斷。": "2. Clinical physicians perform physical exams and diagnosis.",
        "零輻射、無侵入性、無痛。": "Non-radiative, non-invasive, painless.",
        "早期發現腦部病變。": "Early detection of brain lesions.",
        "檢測冠狀動脈阻塞與鈣化。": "Assessment of coronary artery obstruction and calcification.",
        "檢查胃部與十二指腸。": "Examination of stomach and duodenum.",
        "檢查大腸與直腸。": "Examination of colon and rectum.",
        "視力、辨色力、眼壓、免散瞳眼底攝影": "Vision, color sense, IOP, and fundus photography.",
        "身高、體重、體脂、血壓、脈搏": "Height, weight, body fat, BP, and pulse.",
        "精美休閒運動服": "Exquisite casual sportswear",
        "豐富精緻料理(葷、素)": "Gourmet meals (Meat/Veg)",
        "書面報告": "Hardcopy report",
        "免費停車服務": "Free parking",
        "心臟腸胃鏡(男)": "Heart & Gastrointestinal (Male)",
        "心臟腸胃鏡(女)": "Heart & Gastrointestinal (Female)",
        "磁振腸胃鏡(男)": "MRI & Gastrointestinal (Male)",
        "磁振腸胃鏡(女)": "MRI & Gastrointestinal (Female)",
        "基礎腸胃鏡(男)": "Basic Gastrointestinal (Male)",
        "基礎腸胃鏡(女)": "Basic Gastrointestinal (Female)",
        "多焦點心肺腦腸胃鏡(男)": "Multi-Focus H/L/B & Gastro (Male)",
        "多焦點心肺腦腸胃鏡(女)": "Multi-Focus H/L/B & Gastro (Female)",
        "全面型 白金防癌護心(男)": "Total Platinum Cancer & Heart (Male)",
        "全面型 白金防癌護心(女)": "Total Platinum Cancer & Heart (Female)",
        "加強型 白金防癌護心(男)": "Enhanced Platinum Cancer & Heart (Male)",
        "加強型 白金防癌護心(女)": "Enhanced Platinum Cancer & Heart (Female)",
        "白金防癌護心(男)": "Platinum Cancer & Heart (Male)",
        "白金防癌護心(女)": "Platinum Cancer & Heart (Female)",
        "菁英型(男)": "Elite Package (Male)",
        "菁英型(女)": "Elite Package (Female)",
        "鼎級全方位(男)": "Supreme Comprehensive (Male)",
        "鼎級全方位(女)": "Supreme Comprehensive (Female)",
        "基礎型(男)": "Basic Package (Male)",
        "基礎型(女)": "Basic Package (Female)",
        "標準型(男)": "Standard Package (Male)",
        "標準型(女)": "Standard Package (Female)",
        "加強型 全身磁振造影 A專案(男)": "Enhanced Whole-Body MRI Project A (Male)",
        "加強型 全身磁振造影 A專案(女)": "Enhanced Whole-Body MRI Project A (Female)",
        "加強型 全身磁振造影 B專案(男)": "Enhanced Whole-Body MRI Project B (Male)",
        "加強型 全身磁振造影 B專案(女)": "Enhanced Whole-Body MRI Project B (Female)",
        "加強型 全身磁振造影 C專案(男)": "Enhanced Whole-Body MRI Project C (Male)",
        "加強型 全身磁振造影 C專案(女)": "Enhanced Whole-Body MRI Project C (Female)",
        "全面型 全身磁振造影 A專案(男)": "Total Whole-Body MRI Project A (Male)",
        "全面型 全身磁振造影 A專案(女)": "Total Whole-Body MRI Project A (Female)",
        "全面型 全身磁振造影 B專案(男)": "Total Whole-Body MRI Project B (Male)",
        "全面型 全身磁振造影 B專案(女)": "Total Whole-Body MRI Project B (Female)",
        "全面型 全身磁振造影 C專案(男)": "Total Whole-Body MRI Project C (Male)",
        "全面型 全身磁振造影 C專案(女)": "Total Whole-Body MRI Project C (Female)",
        "1.放射科專科醫師影像診斷分析\n 2.專科醫師解說報告與醫療諮詢": "1. Radiologist diagnostic analysis\n 2. Specialist consultation & report explanation",
        "高階雙源心臟電腦斷層(冠狀動脈鈣化與阻塞)": "High-End Dual-Source Cardiac CT (Calcification/Obstruction)",
        "高階雙源心臟電腦斷層(主動脈、肺動脈、心臟功能分析)": "High-End Dual-Source Cardiac CT (Aorta/Pulmonary/Function)",
        "頸動脈超音波、心臟超音波、乳房超音波(限女性)": "Carotid, Cardiac, and Breast Ultrasound (Female Only)",
        "上腹部超音波、下腹部超音波": "Upper and Lower Abdomen Ultrasound",
        "甲狀腺超音波": "Thyroid Ultrasound",
        "婦科超音波(限女性)": "Gynecological Ultrasound (Female Only)",
        "骨盆腔超音波(限男性)": "Pelvic Ultrasound (Male Only)",
        "無痛胃鏡檢查": "Painless Gastroscopy",
        "無痛大腸鏡檢查": "Painless Colonoscopy",
        "飯前血糖(Glucose AC)、醣化血色素(HbA1C)": "Fasting Glucose (AC), HbA1C",
        "總膽固醇、三酸甘油脂、高密度脂蛋白、低密度脂蛋白": "Total Cholesterol, Triglycerides, HDL, LDL",
        "癌胚胎抗原(CEA)、甲型胎兒蛋白(AFP)、攝護腺特異性抗原(PSA/限男性)、腫瘤抗原(CA-125/限女性)": "CEA, AFP, PSA (Male Only), CA-125 (Female Only)",
        "消化器官腫瘤指數(CA-199)、癌抗原21-1 (Cyfra21-1)、EB病毒外鞘抗體 (EBV VCA-IgA)": "CA-199, Cyfra 21-1, EBV VCA-IgA",
        "尿液常規及尿沉渣檢查": "Urinalysis and Sediment Analysis",
        "糞便潛血免疫法": "Fecal Occult Blood Test (iFOBT)",
        "醫師理學檢查、總結解說報告": "Physical Examination and Final Report Review",
        "1.放射科醫師與專任醫師共同影像診斷\n 2.放射科醫師影像診斷分析與專任醫師對位服務": "1. Radiologists & Specialists diagnostic co-review\n 2. Image analysis and medical alignment service",
        "由電腦斷層影像診斷，測知受檢者冠狀動脈是否有鈣化或阻塞之情形。": "CT imaging to detect coronary artery calcification or obstruction.",
        "利用電腦斷層影像，分析主動脈、肺動脈、心臟肌肉與瓣膜功能。": "Analyze aorta, pulmonary artery, cardiac muscle, and valve function.",
        "高階影像分析": "Advanced Image Analysis",
        "由各科專案解說": "Explanation by various specialists"
    }

    d.update(updates)
    with open(dict_file, 'w', encoding='utf-8') as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
    print("大規模更新完成！")

if __name__ == "__main__":
    massive_update()
